### ISSUE TITLE
migration of nested objects in CRIS entities: improper handling of optional nested fields

### ISSUE THREAD

**Issue by saschaszott** [4Science/DSpace#398]
In DSC5 we are using _nested objects_ to model **affilations** in researcher profiles. Each affiliation consists of 4 fields: **org unit** (ou pointer; mandatory), **role** (mandatory), **start date** (optional), **end date** (optional).

Currently, we have several affilations **without** start date and / or end date.

For example, in DSC5 we have one RP with 2 affiliations (screen shot)

![image](https://github.com/4Science/DSpace/assets/952735/aa7ccbdb-5349-431c-a49a-9d8939a577ee)

Currently, the CRIS migration procedure (Pentaho transformation) inverts the order of affilations. This is due to step _Sort position_ in `entity_migration.krt` (ascending = N)

The expected migration result of the given example RP is:

![image](https://github.com/4Science/DSpace/assets/952735/e70b74ff-3758-44e4-be25-094f69e24a6a)

Currently, DSC7 produces an **invalid migration result** in case of affiliations with optional fields (as in the given example):

![image](https://github.com/4Science/DSpace/assets/952735/7a1e1518-a3d4-4f87-a5d4-e7f8e4ff9fbe)

In this example the assignment of end date is not correct.

This bug is caused by the Pentaho migration step _Select values 4_ which removes `nested_object_id` and `positiondef` in each row of the stream. This means that subsequent migration steps cannot determine the correct assignments of nested fields to a given affiliation (nested object).

This bug affects the migration of RPs that have at least 2 affilations with missing nested fields.

We'll provide a bugfix (adaption of the Pentaho migration).

**Comment by atarix83** [comment]
Hi @saschaszott 

thanks for opening the issue, anyway this should be already resolved with https://github.com/4Science/DSpace/pull/276.

Feel free to re-open again the issue if is not working for you

**Comment by saschaszott** [comment]
Hi @atarix83 , the PR (276) you mentioned, does not fix the problem. We have integrated #276 into our code base and are able to reproduce the bug.

**Comment by saschaszott** [comment]
@atarix83 , the problem is raised in the pentaho transformation step named _Select values 4_. In this early transformation step the important sorting information in `nested_object_id` and `positiondef` is removed. We have fixed the Pentaho transformation (requires additional steps) locally. Let me know if you are interested in a PR.

**Comment by atarix83** [comment]
@saschaszott 

yes please open a PR when you can, so we can verify. Thanks

**Comment by saschaszott** [comment]
@atarix83 , sorry for the long pause, but today I was able to reproduce the problem described above with the latest version of DSC (2023.02.02). To illustrate the problem, I'll give you an example of a nested affiliation object (with 3 entries):

![image](https://github.com/4Science/DSpace/assets/952735/f29a9242-3326-40d2-b7b4-ce4df7b2d3ef)

In the migrated RP you'll find an incorrect state

![image](https://github.com/4Science/DSpace/assets/952735/d865dbb7-d51d-4a50-af1c-e32e50fedb19)

As you can see in the metadata full view, there is an uneven number of affiliation.startDate and affiliation.endDate fields

![image](https://github.com/4Science/DSpace/assets/952735/21d11200-9c39-4d61-8e31-091da68ad21b)

**Comment by saschaszott** [comment]
To better illustrate the change in the entity migration transformation, I'll provide a before-after comparison of the change in `entity-migration.ktr` we propse:

![image](https://github.com/4Science/DSpace/assets/952735/6c3ea1a2-4d1f-4e89-a4c5-b61401f92eb7)

![image](https://github.com/4Science/DSpace/assets/952735/9afc41d6-f28a-41e6-82bc-7b0c6a34644c)

**Comment by saschaszott** [comment]
You can find our proposed bugfix in PR #425 .
